stages:
  - test
  - build_sdist
  - build_rpm


before_script:
  - export LANG=en_US.UTF-8


test:
  image: registry.fedoraproject.org/fedora:31
  stage: test

  script:
    - dnf -y install rpmlint tox
    - rpmlint python-advisory-parser.spec
    - tox


build_sdist:
  image: registry.fedoraproject.org/fedora:31
  stage: build_sdist

  when: manual
  allow_failure: false  # Do not execute RPM jobs below unless this one is run/succeeds.

  script:
    - python3 setup.py clean sdist

  artifacts:
    paths:
      - dist/


rpm:fedora-latest:
  # Build latest Fedora RPM
  image: registry.fedoraproject.org/fedora:31
  stage: build_rpm

  dependencies:
    - build_sdist

  script:
    - bash -e build_rpm.sh "fedora" "python-advisory-parser.spec"

  artifacts:
    paths:
      - SRPMS/
      - RPMS/


rpm:fedora-secondary:
  # Build secondary Fedora RPM
  image: registry.fedoraproject.org/fedora:30
  stage: build_rpm

  dependencies:
    - build_sdist

  script:
    - bash -e build_rpm.sh "fedora" "python-advisory-parser.spec"

  artifacts:
    paths:
      - SRPMS/
      - RPMS/


rpm:el7:
  # Build RPM for Enterprise Linux 7 (CentOS 7, RHEL 7)
  image: centos:7
  stage: build_rpm

  dependencies:
    - build_sdist

  script:
    - bash -e build_rpm.sh "el7" "python-advisory-parser.spec"

  artifacts:
    paths:
      - SRPMS/
      - RPMS/


rpm:el8:
  # Build RPM for Enterprise Linux 8 (CentOS 8, RHEL 8)
  image: centos:8
  stage: build_rpm

  dependencies:
    - build_sdist

  script:
    - bash -e build_rpm.sh "el8" "python-advisory-parser.spec"

  artifacts:
    paths:
      - SRPMS/
      - RPMS/
