language: python

notifications:
  email: false
  on_success: never
  on_failure: always

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -e .
  - pip install -r devel-requirements.txt

script:
  - pytest tests
