language: python

notifications:
  email: false
  on_success: never
  on_failure: always

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e .
  - pip install -r devel-requirements.txt

script:
  - pytest tests
